services:
  odm_backend:
    build: ./src/backend
    ports:
      - "6004:6004"
    volumes:
      - odm:/usr/src/odm_backend
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker
      - //./pipe/docker_engine://./pipe/docker_engine
    env_file:
      - .env
    # environment:
    #   - RUST_LOG=info
    networks:
      - main

  odm_frontend:
    build: ./src/frontend
    ports:
      - "7004:7004"
      - "4000:4000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - odm_backend
    env_file:
      - .env.docker
    networks:
      - main

volumes:
  odm: 
    external: true

networks:
  main:
    external: true