services:
  odm_backend:
    build: ./src/backend
    ports:
      - "6004:6004"
    volumes:
      - odm:/usr/src/odm_backend
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker
      - //./pipe/docker_engine://./pipe/docker_engine
    depends_on:
      - odm_database
    environment:
      - RUST_LOG=info
    networks:
      - main

  odm_frontend:
    build: ./src/frontend
    ports:
      - "7004:7004"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - odm_backend
    networks:
      - main

  odm_database:
    image: postgres:latest
    ports:
      - "5004:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=my_database
    volumes:
      - odm:/var/lib/postgres
    networks:
      - main

volumes:
  odm: 
    external: true

networks:
  main:
    external: true